### ISSUE TITLE
suggestion

### ISSUE THREAD

**Issue by OwOsucksAwesomeMinecraftbossAlissha6TRM** [Sascha-T/create-computing#5]
make it so you can control the rotational speed controller with a computer. Would be useful in some cases.

and possibly make it so u can control the speed of creative engine 
AND/OR 
the speed of the electric motor from create crafts & additions (if possible)

**Comment by awesomebossdj7** [comment]
nevermind i just figured out the last one is already a thing, basically adds my idea.
